name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - 'packages/container/**' # when change occurs on master branch inside path container folder

defaults:
  run:
    working-directory: packages/container # set working directory

jobs:
  build:
    runs-on: ubuntu-18.04 # use a ubuntu/linux based virtul machine

    steps:
      - uses: actions/checkout@v2 # checkout the code in the virtual machine
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2 # deploy to aws using aws cli
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # to invalidate the index.html script tags (cache burst) we need to invalidate the distribution
      # otherwise on rebuild the index.html will still point to old main.[hash].js
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/container/latest/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
